var WORK=[
  {id:"mot",name:"MOT test",buy:"MOT",hrs:1,plo:0,phi:0,note:"Standard Class 4 MOT. No parts."},
  {id:"service",name:"Interim service (oil + filter)",buy:"service kit",hrs:1,plo:40,phi:95,note:"Oil and filter. Full service is the next step."},
  {id:"full",name:"Full service",buy:"full service kit",hrs:1.8,plo:70,phi:160,note:"Oil, filters and plugs or fuel filter."},
  {id:"major",name:"Major service",buy:"major service kit",hrs:2.5,plo:110,phi:260,note:"Full service plus extra checks and fluids."},
  {id:"beltwp",name:"Timing belt + water pump",buy:"timing belt kit water pump",hrs:5,plo:90,phi:220,note:"Do the pump while it is open. Some engines use a chain."},
  {id:"belt",name:"Timing belt only",buy:"timing belt kit",hrs:4.5,plo:45,phi:140,note:"Usually false economy not to do the pump."},
  {id:"wetbelt",name:"Wet belt / belt-in-oil",buy:"wet belt kit",hrs:6.5,plo:180,phi:420,note:"Some Ford and Volvo petrol engines. Check the history."},
  {id:"chain",name:"Timing chain kit",buy:"timing chain kit",hrs:8,plo:180,phi:480,note:"Rattle on start-up is the usual clue."},
  {id:"aux",name:"Auxiliary belt + tensioner",buy:"auxiliary belt tensioner",hrs:1.2,plo:25,phi:90,note:""},
  {id:"clutch",name:"Clutch kit",buy:"clutch kit",hrs:6.5,plo:180,phi:380,note:"Gearbox out. Dual-mass flywheel extra if worn."},
  {id:"clutchdmf",name:"Clutch + dual-mass flywheel",buy:"clutch kit dual mass flywheel",hrs:7,plo:380,phi:750,note:"Common on diesels."},
  {id:"gearbox",name:"Gearbox oil change",buy:"gearbox oil",hrs:1.2,plo:35,phi:90,note:""},
  {id:"dsg",name:"DSG / auto gearbox service",buy:"DSG gearbox service kit",hrs:2,plo:80,phi:180,note:"Filter and oil on wet-clutch autos."},
  {id:"haldex",name:"Haldex / AWD coupling service",buy:"haldex filter oil",hrs:1.5,plo:40,phi:110,note:"Worth doing on AWD Volvos and VAG cars."},
  {id:"shaft",name:"Driveshaft (one side)",buy:"driveshaft",hrs:2.2,plo:90,phi:240,note:"Clicking on full lock is the usual clue."},
  {id:"cvboot",name:"CV gaiter",buy:"CV boot kit",hrs:1.4,plo:15,phi:45,note:"Split gaiter fails an MOT if grease is thrown."},
  {id:"propshaft",name:"Propshaft centre bearing",buy:"propshaft centre bearing",hrs:2,plo:40,phi:120,note:""},
  {id:"fpads",name:"Front pads and discs",buy:"front brake pads discs",hrs:1.6,plo:85,phi:240,note:""},
  {id:"rpads",name:"Rear pads and discs",buy:"rear brake pads discs",hrs:1.6,plo:75,phi:220,note:""},
  {id:"pads",name:"Front pads only",buy:"front brake pads",hrs:0.9,plo:25,phi:70,note:""},
  {id:"caliper",name:"Brake caliper (one)",buy:"brake caliper",hrs:1.4,plo:50,phi:160,note:""},
  {id:"handbrake",name:"Handbrake cable",buy:"handbrake cable",hrs:1.5,plo:20,phi:70,note:""},
  {id:"brakefluid",name:"Brake fluid change",buy:"brake fluid",hrs:0.8,plo:8,phi:20,note:"Due every 2 years on most cars."},
  {id:"abs",name:"ABS sensor",buy:"ABS sensor",hrs:0.8,plo:20,phi:70,note:""},
  {id:"batt",name:"Battery",buy:"car battery",hrs:0.5,plo:80,phi:200,note:"Stop-start AGM batteries sit at the top of the range."},
  {id:"alt",name:"Alternator",buy:"alternator",hrs:2.2,plo:130,phi:380,note:""},
  {id:"start",name:"Starter motor",buy:"starter motor",hrs:2,plo:110,phi:300,note:""},
  {id:"damp",name:"Pair of dampers",buy:"shock absorbers",hrs:2.2,plo:130,phi:380,note:"Air springs are a different, dearer job."},
  {id:"spring",name:"Coil spring (one)",buy:"coil spring",hrs:1.3,plo:40,phi:120,note:""},
  {id:"bearing",name:"Wheel bearing (one)",buy:"wheel bearing",hrs:1.8,plo:35,phi:120,note:"Growl that rises with speed."},
  {id:"hub",name:"Wheel hub assembly",buy:"wheel hub",hrs:1.8,plo:50,phi:160,note:""},
  {id:"drop",name:"Anti-roll drop link",buy:"drop link",hrs:0.6,plo:10,phi:35,note:"Clunk over bumps."},
  {id:"track",name:"Track-rod end",buy:"track rod end",hrs:0.8,plo:15,phi:45,note:"Then needs a tracking check."},
  {id:"rack",name:"Steering rack",buy:"steering rack",hrs:4,plo:180,phi:480,note:""},
  {id:"wishbone",name:"Wishbone / lower arm",buy:"wishbone",hrs:1.8,plo:50,phi:180,note:""},
  {id:"balljoint",name:"Ball joint",buy:"ball joint",hrs:1.2,plo:20,phi:70,note:""},
  {id:"bush",name:"Control arm bushes",buy:"control arm bushes",hrs:2,plo:20,phi:80,note:""},
  {id:"tracking",name:"Four-wheel tracking",buy:"wheel alignment",hrs:1,plo:0,phi:0,note:"No parts. Tracking, not an alignment package."},
  {id:"exhaust",name:"Centre exhaust section",buy:"exhaust centre section",hrs:1.2,plo:60,phi:180,note:""},
  {id:"backbox",name:"Exhaust back box",buy:"exhaust back box",hrs:1,plo:70,phi:220,note:"Rear silencer."},
  {id:"downpipe",name:"Downpipe",buy:"exhaust downpipe",hrs:1.8,plo:80,phi:260,note:""},
  {id:"flexi",name:"Exhaust flexi pipe",buy:"exhaust flexi pipe",hrs:1.2,plo:25,phi:80,note:""},
  {id:"manifold",name:"Exhaust manifold",buy:"exhaust manifold",hrs:3,plo:80,phi:260,note:""},
  {id:"cat",name:"Catalytic converter",buy:"catalytic converter",hrs:1.8,plo:180,phi:520,note:"Theft and MOT emissions both drive this."},
  {id:"dpf",name:"DPF clean",buy:"DPF clean",hrs:2,plo:80,phi:220,note:"Forced regen or off-car clean. Replacement is far more."},
  {id:"dpfr",name:"DPF replacement",buy:"DPF diesel particulate filter",hrs:3,plo:350,phi:900,note:""},
  {id:"egr",name:"EGR valve",buy:"EGR valve",hrs:2,plo:80,phi:260,note:""},
  {id:"turbo",name:"Turbocharger",buy:"turbocharger",hrs:4.5,plo:280,phi:750,note:""},
  {id:"injector",name:"Injector (one)",buy:"fuel injector",hrs:1.6,plo:90,phi:280,note:""},
  {id:"glow",name:"Glow plugs (set)",buy:"glow plugs",hrs:1.2,plo:40,phi:120,note:"Diesel cold-start."},
  {id:"hpump",name:"High pressure fuel pump",buy:"high pressure fuel pump",hrs:3.5,plo:180,phi:480,note:""},
  {id:"fuelpump",name:"In-tank fuel pump",buy:"fuel pump",hrs:2.2,plo:80,phi:220,note:""},
  {id:"thermo",name:"Thermostat",buy:"thermostat",hrs:1.6,plo:20,phi:70,note:""},
  {id:"rad",name:"Radiator",buy:"radiator",hrs:2.2,plo:70,phi:220,note:""},
  {id:"radfan",name:"Radiator fan",buy:"radiator fan",hrs:1.4,plo:50,phi:160,note:""},
  {id:"wpump",name:"Water pump only",buy:"water pump",hrs:3,plo:40,phi:140,note:"Often cheaper with the timing belt."},
  {id:"hose",name:"Coolant hose",buy:"coolant hose",hrs:0.8,plo:10,phi:40,note:""},
  {id:"exp",name:"Expansion tank",buy:"expansion tank",hrs:0.8,plo:20,phi:70,note:""},
  {id:"headg",name:"Head gasket",buy:"head gasket set",hrs:12,plo:80,phi:250,note:"Big job. Estimate only — inspect first."},
  {id:"coil",name:"Coil pack",buy:"ignition coil",hrs:0.6,plo:25,phi:90,note:""},
  {id:"plugs",name:"Spark plugs",buy:"spark plugs",hrs:0.8,plo:20,phi:70,note:"Petrol / hybrid."},
  {id:"lambda",name:"Lambda sensor",buy:"lambda sensor",hrs:0.9,plo:40,phi:140,note:""},
  {id:"maf",name:"MAF sensor",buy:"MAF sensor",hrs:0.5,plo:50,phi:180,note:""},
  {id:"map",name:"MAP sensor",buy:"MAP sensor",hrs:0.5,plo:30,phi:90,note:""},
  {id:"cam",name:"Camshaft sensor",buy:"camshaft sensor",hrs:0.6,plo:20,phi:70,note:""},
  {id:"crank",name:"Crankshaft sensor",buy:"crankshaft sensor",hrs:0.8,plo:20,phi:80,note:""},
  {id:"tstatsw",name:"Coolant temperature sensor",buy:"coolant temperature sensor",hrs:0.6,plo:10,phi:40,note:""},
  {id:"windscreen",name:"Windscreen",buy:"windscreen",hrs:2,plo:120,phi:380,note:"Often claimed on glass insurance."},
  {id:"rearglass",name:"Rear screen",buy:"rear windscreen",hrs:2.2,plo:140,phi:420,note:""},
  {id:"wipers",name:"Wiper blades (pair)",buy:"wiper blades",hrs:0.3,plo:12,phi:40,note:""},
  {id:"wipermotor",name:"Wiper motor",buy:"wiper motor",hrs:1.2,plo:40,phi:140,note:""},
  {id:"bootstrut",name:"Boot strut (pair)",buy:"boot strut",hrs:0.4,plo:20,phi:60,note:""},
  {id:"bonnetstrut",name:"Bonnet strut (pair)",buy:"bonnet strut",hrs:0.4,plo:15,phi:50,note:""},
  {id:"windowreg",name:"Window regulator",buy:"window regulator",hrs:1.6,plo:40,phi:140,note:""},
  {id:"windowsw",name:"Window switch",buy:"window switch",hrs:0.5,plo:20,phi:80,note:""},
  {id:"acregas",name:"Air-con re-gas",buy:"air con re gas",hrs:1,plo:35,phi:80,note:"Leak find is extra if it will not hold gas."},
  {id:"accomp",name:"Air-con compressor",buy:"air con compressor",hrs:3,plo:180,phi:480,note:""},
  {id:"heater",name:"Heater matrix",buy:"heater matrix",hrs:6,plo:40,phi:140,note:"Dash-out on many cars."},
  {id:"tyres2",name:"Two tyres fitted",buy:"car tyres",hrs:0.8,plo:140,phi:320,note:"Budget to mid-range pair, fitted."},
  {id:"tyres4",name:"Four tyres fitted",buy:"car tyres",hrs:1.2,plo:280,phi:640,note:"Budget to mid-range set, fitted."},
  {id:"puncture",name:"Puncture repair",buy:"puncture repair",hrs:0.5,plo:15,phi:35,note:""},
  {id:"wing",name:"Front wing",buy:"front wing",hrs:2,plo:80,phi:280,note:"Paint extra unless supplied painted."},
  {id:"wingr",name:"Rear wing / quarter",buy:"rear wing",hrs:4,plo:150,phi:450,note:"Often a bodyshop job."},
  {id:"bonnet",name:"Bonnet",buy:"bonnet",hrs:1.5,plo:120,phi:380,note:"Paint extra unless supplied painted."},
  {id:"bootlid",name:"Boot lid / tailgate",buy:"boot lid",hrs:2,plo:150,phi:480,note:""},
  {id:"door",name:"Door shell",buy:"car door",hrs:2.5,plo:150,phi:480,note:""},
  {id:"bumperf",name:"Front bumper",buy:"front bumper",hrs:1.5,plo:80,phi:280,note:"Parking sensors extra."},
  {id:"bumperr",name:"Rear bumper",buy:"rear bumper",hrs:1.5,plo:80,phi:280,note:""},
  {id:"grille",name:"Front grille",buy:"front grille",hrs:0.6,plo:30,phi:140,note:""},
  {id:"arch",name:"Wheel arch liner",buy:"wheel arch liner",hrs:0.6,plo:15,phi:50,note:""},
  {id:"sill",name:"Sill repair",buy:"sill panel",hrs:4,plo:40,phi:160,note:"Rust repair. Bodyshop hours vary a lot."},
  {id:"mirror",name:"Door mirror",buy:"door mirror",hrs:0.6,plo:40,phi:180,note:""},
  {id:"mirrorg",name:"Door mirror glass",buy:"door mirror glass",hrs:0.3,plo:10,phi:40,note:""},
  {id:"handle",name:"Door handle",buy:"door handle",hrs:0.8,plo:20,phi:90,note:""},
  {id:"lock",name:"Door lock actuator",buy:"door lock actuator",hrs:1.2,plo:40,phi:140,note:""},
  {id:"headlight",name:"Headlight unit",buy:"headlight",hrs:1,plo:80,phi:350,note:"LED / xenon units sit at the top."},
  {id:"taillight",name:"Rear light cluster",buy:"rear light cluster",hrs:0.6,plo:40,phi:180,note:""},
  {id:"fog",name:"Fog light",buy:"fog light",hrs:0.4,plo:15,phi:70,note:""},
  {id:"indicator",name:"Indicator / repeater",buy:"indicator lamp",hrs:0.3,plo:8,phi:40,note:""},
  {id:"bulb",name:"Headlight bulb",buy:"headlight bulb",hrs:0.4,plo:8,phi:35,note:""},
  {id:"hid",name:"Xenon / HID bulb",buy:"xenon hid bulb",hrs:0.5,plo:30,phi:90,note:""},
  {id:"ballast",name:"HID ballast",buy:"HID ballast",hrs:0.8,plo:40,phi:140,note:""},
  {id:"numberplate",name:"Number plate light",buy:"number plate light",hrs:0.3,plo:5,phi:20,note:""},
  {id:"switch",name:"Light switch",buy:"headlight switch",hrs:0.6,plo:20,phi:80,note:""},
  {id:"indicatorstk",name:"Indicator stalk",buy:"indicator stalk",hrs:0.8,plo:25,phi:90,note:""},
  {id:"horn",name:"Horn",buy:"car horn",hrs:0.5,plo:10,phi:40,note:""},
  {id:"washer",name:"Washer pump",buy:"washer pump",hrs:0.6,plo:8,phi:30,note:""},
  {id:"egrcool",name:"EGR cooler",buy:"EGR cooler",hrs:3,plo:120,phi:320,note:""},
  {id:"inlet",name:"Inlet manifold",buy:"inlet manifold",hrs:3,plo:80,phi:260,note:""},
  {id:"throttle",name:"Throttle body",buy:"throttle body",hrs:1.2,plo:80,phi:260,note:""},
  {id:"flywheel",name:"Dual-mass flywheel only",buy:"dual mass flywheel",hrs:6.5,plo:220,phi:520,note:"Usually done with the clutch."},
  {id:"slave",name:"Clutch slave cylinder",buy:"clutch slave cylinder",hrs:1.5,plo:30,phi:90,note:""},
  {id:"master",name:"Clutch master cylinder",buy:"clutch master cylinder",hrs:1.5,plo:30,phi:90,note:""},
  {id:"radiatorc",name:"Condenser",buy:"air con condenser",hrs:1.8,plo:70,phi:220,note:""},
  {id:"inter",name:"Intercooler",buy:"intercooler",hrs:1.8,plo:80,phi:260,note:""},
  {id:"mount",name:"Engine mount",buy:"engine mount",hrs:1.4,plo:30,phi:120,note:""},
  {id:"gboxmount",name:"Gearbox mount",buy:"gearbox mount",hrs:1.2,plo:30,phi:110,note:""},
  {id:"sump",name:"Sump gasket / sump",buy:"sump gasket",hrs:2.5,plo:15,phi:80,note:""},
  {id:"rocker",name:"Rocker cover gasket",buy:"rocker cover gasket",hrs:1.2,plo:10,phi:40,note:""},
  {id:"pcv",name:"PCV / oil separator",buy:"PCV valve",hrs:1,plo:25,phi:120,note:""},
  {id:"thermostath",name:"Thermostat housing",buy:"thermostat housing",hrs:1.8,plo:25,phi:90,note:""},
  {id:"vacpump",name:"Vacuum pump",buy:"brake vacuum pump",hrs:1.8,plo:80,phi:220,note:""},
  {id:"absmod",name:"ABS pump / module",buy:"ABS module",hrs:2.5,plo:150,phi:480,note:"Often needs coding."},
  {id:"ecu",name:"ECU repair / swap",buy:"engine ECU",hrs:2,plo:150,phi:600,note:"Coding extra."},
  {id:"key",name:"Spare key / fob",buy:"car key fob",hrs:1,plo:80,phi:280,note:"Programming extra at a locksmith or dealer."},
  {id:"lockset",name:"Ignition barrel",buy:"ignition barrel",hrs:1.5,plo:40,phi:140,note:""},
  {id:"seatbelt",name:"Seatbelt",buy:"seatbelt",hrs:1,plo:40,phi:140,note:""},
  {id:"airbag",name:"Clock spring / airbag squib",buy:"clock spring",hrs:1.2,plo:30,phi:120,note:""},
  {id:"handbrakel",name:"Electric handbrake motor",buy:"electric handbrake motor",hrs:1.4,plo:80,phi:260,note:""},
  {id:"sensorp",name:"Parking sensor",buy:"parking sensor",hrs:0.5,plo:15,phi:60,note:""},
  {id:"camera",name:"Reversing camera",buy:"reversing camera",hrs:1,plo:40,phi:160,note:""},
  {id:"dampair",name:"Air suspension bag",buy:"air suspension bag",hrs:2,plo:120,phi:350,note:""},
  {id:"compair",name:"Air suspension compressor",buy:"air suspension compressor",hrs:2,plo:180,phi:480,note:""}
];
