var WORK=[
  {id:"mot",name:"MOT test",buy:"MOT",hrs:1,plo:0,phi:0,note:"Standard Class 4 MOT. No parts."},
  {id:"service",name:"Interim service (oil + filter)",buy:"service kit",hrs:1,plo:40,phi:95,note:"Oil and filter. Full service is the next step."},
  {id:"full",name:"Full service",buy:"full service kit",hrs:1.8,plo:70,phi:160,note:"Oil, filters and plugs or fuel filter."},
  {id:"major",name:"Major service",buy:"major service kit",hrs:2.5,plo:110,phi:260,note:"Full service plus extra checks and fluids."},
  {id:"beltwp",name:"Timing belt + water pump",buy:"timing belt kit water pump",hrs:5,plo:90,phi:220,note:"Do the pump while it is open. Some engines use a chain."},
  {id:"belt",name:"Timing belt only",buy:"timing belt kit",hrs:4.5,plo:45,phi:140,note:"Usually false economy not to do the pump."},
  {id:"wetbelt",name:"Wet belt / belt-in-oil",buy:"wet belt kit",hrs:6.5,plo:180,phi:420,note:"Some Ford and Volvo petrol engines. Check the history."},
  {id:"chain",name:"Timing chain kit",buy:"timing chain kit",hrs:8,plo:180,phi:480,note:"Rattle on start-up is the usual clue."},
  {id:"aux",name:"Auxiliary belt + tensioner",buy:"auxiliary belt tensioner",hrs:1.2,plo:25,phi:90,note:""},
  {id:"clutch",name:"Clutch kit",buy:"clutch kit",hrs:6.5,plo:180,phi:380,note:"Gearbox out. Dual-mass flywheel extra if worn."},
  {id:"clutchdmf",name:"Clutch + dual-mass flywheel",buy:"clutch kit dual mass flywheel",hrs:7,plo:380,phi:750,note:"Common on diesels."},
  {id:"gearbox",name:"Gearbox oil change",buy:"gearbox oil",hrs:1.2,plo:35,phi:90,note:""},
  {id:"haldex",name:"Haldex / AWD coupling service",buy:"haldex filter oil",hrs:1.5,plo:40,phi:110,note:"Worth doing on AWD Volvos and VAG cars."},
  {id:"shaft",name:"Driveshaft (one side)",buy:"driveshaft",hrs:2.2,plo:90,phi:240,note:"Clicking on full lock is the usual clue."},
  {id:"cvboot",name:"CV gaiter",buy:"CV boot kit",hrs:1.4,plo:15,phi:45,note:"Split gaiter fails an MOT if grease is thrown."},
  {id:"fpads",name:"Front pads and discs",buy:"front brake pads discs",hrs:1.6,plo:85,phi:240,note:""},
  {id:"rpads",name:"Rear pads and discs",buy:"rear brake pads discs",hrs:1.6,plo:75,phi:220,note:""},
  {id:"pads",name:"Front pads only",buy:"front brake pads",hrs:0.9,plo:25,phi:70,note:""},
  {id:"caliper",name:"Brake caliper (one)",buy:"brake caliper",hrs:1.4,plo:50,phi:160,note:""},
  {id:"handbrake",name:"Handbrake cable",buy:"handbrake cable",hrs:1.5,plo:20,phi:70,note:""},
  {id:"brakefluid",name:"Brake fluid change",buy:"brake fluid",hrs:0.8,plo:8,phi:20,note:"Due every 2 years on most cars."},
  {id:"batt",name:"Battery",buy:"car battery",hrs:0.5,plo:80,phi:200,note:"Stop-start AGM batteries sit at the top of the range."},
  {id:"alt",name:"Alternator",buy:"alternator",hrs:2.2,plo:130,phi:380,note:""},
  {id:"start",name:"Starter motor",buy:"starter motor",hrs:2,plo:110,phi:300,note:""},
  {id:"damp",name:"Pair of dampers",buy:"shock absorbers",hrs:2.2,plo:130,phi:380,note:"Air springs are a different, dearer job."},
  {id:"spring",name:"Coil spring (one)",buy:"coil spring",hrs:1.3,plo:40,phi:120,note:""},
  {id:"bearing",name:"Wheel bearing (one)",buy:"wheel bearing",hrs:1.8,plo:35,phi:120,note:"Growl that rises with speed."},
  {id:"drop",name:"Anti-roll drop link",buy:"drop link",hrs:0.6,plo:10,phi:35,note:"Clunk over bumps."},
  {id:"track",name:"Track-rod end",buy:"track rod end",hrs:0.8,plo:15,phi:45,note:"Then needs a tracking check."},
  {id:"wishbone",name:"Wishbone / lower arm",buy:"wishbone",hrs:1.8,plo:50,phi:180,note:""},
  {id:"tracking",name:"Four-wheel tracking",buy:"wheel alignment",hrs:1,plo:0,phi:0,note:"No parts. Tracking, not an alignment package."},
  {id:"exhaust",name:"Centre exhaust section",buy:"exhaust centre section",hrs:1.2,plo:60,phi:180,note:""},
  {id:"cat",name:"Catalytic converter",buy:"catalytic converter",hrs:1.8,plo:180,phi:520,note:"Theft and MOT emissions both drive this."},
  {id:"dpf",name:"DPF clean",buy:"DPF clean",hrs:2,plo:80,phi:220,note:"Forced regen or off-car clean. Replacement is far more."},
  {id:"egr",name:"EGR valve",buy:"EGR valve",hrs:2,plo:80,phi:260,note:""},
  {id:"turbo",name:"Turbocharger",buy:"turbocharger",hrs:4.5,plo:280,phi:750,note:""},
  {id:"injector",name:"Injector (one)",buy:"fuel injector",hrs:1.6,plo:90,phi:280,note:""},
  {id:"glow",name:"Glow plugs (set)",buy:"glow plugs",hrs:1.2,plo:40,phi:120,note:"Diesel cold-start."},
  {id:"thermo",name:"Thermostat",buy:"thermostat",hrs:1.6,plo:20,phi:70,note:""},
  {id:"rad",name:"Radiator",buy:"radiator",hrs:2.2,plo:70,phi:220,note:""},
  {id:"wpump",name:"Water pump only",buy:"water pump",hrs:3,plo:40,phi:140,note:"Often cheaper with the timing belt."},
  {id:"headg",name:"Head gasket",buy:"head gasket set",hrs:12,plo:80,phi:250,note:"Big job. Estimate only — inspect first."},
  {id:"coil",name:"Coil pack",buy:"ignition coil",hrs:0.6,plo:25,phi:90,note:""},
  {id:"plugs",name:"Spark plugs",buy:"spark plugs",hrs:0.8,plo:20,phi:70,note:"Petrol / hybrid."},
  {id:"lambda",name:"Lambda sensor",buy:"lambda sensor",hrs:0.9,plo:40,phi:140,note:""},
  {id:"maf",name:"MAF sensor",buy:"MAF sensor",hrs:0.5,plo:50,phi:180,note:""},
  {id:"windscreen",name:"Windscreen",buy:"windscreen",hrs:2,plo:120,phi:380,note:"Often claimed on glass insurance."},
  {id:"wipers",name:"Wiper blades (pair)",buy:"wiper blades",hrs:0.3,plo:12,phi:40,note:""},
  {id:"bootstrut",name:"Boot strut (pair)",buy:"boot strut",hrs:0.4,plo:20,phi:60,note:""},
  {id:"windowreg",name:"Window regulator",buy:"window regulator",hrs:1.6,plo:40,phi:140,note:""},
  {id:"acregas",name:"Air-con re-gas",buy:"air con re gas",hrs:1,plo:35,phi:80,note:"Leak find is extra if it will not hold gas."},
  {id:"tyres2",name:"Two tyres fitted",buy:"car tyres",hrs:0.8,plo:140,phi:320,note:"Budget to mid-range pair, fitted."},
  {id:"tyres4",name:"Four tyres fitted",buy:"car tyres",hrs:1.2,plo:280,phi:640,note:"Budget to mid-range set, fitted."},
  {id:"puncture",name:"Puncture repair",buy:"puncture repair",hrs:0.5,plo:15,phi:35,note:""}
];
